#!/bin/bash
set -euo pipefail

LIBNAME=libm3.a

DEFAULT="iphoneos-arm64 iphonesimulator-arm64 iphonesimulator-x86_64 macosx-x86_64"

options() {
  sdk=$1
  arch=$2
  case "$sdk" in
    iphoneos|iphonesimulator)
      echo -mios-version-min=13.0
      ;;
  esac
  case "$sdk" in
    iphoneos)
      echo -target $arch-ios
      ;;
    iphonesimulator)
      echo -target $arch-ios-simulator
      ;;
    macosx)
      echo -target $arch-macos
      ;;
  esac
}

if [ $# -eq 0 ]; then
  echo "usage: $0 <wasm3-dir> <combo> .., where combo is all or $default" 1>&2
  exit 1
fi

wasmdir=$1
shift

if [ $# -eq 1 -a $1 = all ]; then
  args="$DEFAULT"
else
  args=$@
fi
echo $args

compile() {
  sdk=$1
  arch=$2
  clang=$3
  ar=$4
  sdkpath=$5
  opts=$(options "$sdk" "$arch")
  objdir="objects-$sdk-$arch"
  rm -rf "$objdir"
  mkdir "$objdir"
  echo "$sdk-$arch"
  (cd "$objdir"
   for f in "$wasmdir"/source/*.c; do
     echo - $(basename "$f")
     (set -o xtrace
      "$clang" -c "$f" $opts \
        -isysroot "$sdkpath" \
        -arch $arch \
        -Dd_m3HasWASI \
        -fembed-bitcode-marker)
   done)
  mkdir -p "lib/$sdk-$arch"
  (set -o xtrace
   "$ar" rcs "lib/$sdk-$arch/$LIBNAME" "$objdir"/*)
}

for arg in $args; do
  sdk=$(echo $arg|cut -d- -f1)
  arch=$(echo $arg|cut -d- -f2)
  echo sdk: $sdk, arch: $arch
  compile $sdk $arch \
   "$(xcrun --sdk $sdk --find clang)" \
    $(xcrun --sdk $sdk --find ar) \
    $(xcrun --sdk $sdk --show-sdk-path)
done
